server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb:failover://localhost/registration?autoReconnect=true
    username: root
    password: 6666!
  sql:
    init:
      platform: mariadb
